import 'simplelightbox/dist/simple-lightbox.min.css';
import './js/category/category.js';
import './js/search/search.js';
import './js/header/activePage.js';
import './js/header/mobMenu.js';
import './js/header/darkTheme.js';
import './js/favorites-recipe/favorites-recipe.js';
import './js/hero/hero.js';
import './js/scroll/up-scroll.js';
