import 'simplelightbox/dist/simple-lightbox.min.css';
import Swiper from 'swiper';
import SlimSelect from 'slim-select';
import './js/category/category.js';
import './js/search/search.js';
import './js/header/activePage.js';
import './js/header/mobMenu.js';
import './js/header/darkTheme.js';
import './js/hero/hero.js';
// import './js/modal/API-modal.js';
// import './js/modal/modal-recipes-rating.js';
// import './js/modal/ranging-modal.js';
import './js/scroll/up-scroll.js';
import './js/footer/footer.js';
import './js/footer/gallery-items.js';
import './js/recipe/recipe-api.js';
import './js/recipe/recipe.js';
