import { hero } from './js/hero/hero';
import { favoritesRecipe } from './js/favorites-recipe/favorites-recipe';
import { header } from './js/header/header';
import { recipe } from './js/recipe/recipe';
import { modal } from './js/modal/modal';
import { pagination } from './js/pagination/pagination';
import { category } from './js/category/category';
import { popular } from './js/popular/popular';
import { Notify } from 'notiflix/build/notiflix-notify-aio';
import axios from 'axios';
import SimpleLightbox from 'simplelightbox';
import 'simplelightbox/dist/simple-lightbox.min.css';
